spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-db.chgeai0qiq90.ap-northeast-2.rds.amazonaws.com:3306/library_db
    username: aws
    password: 1q2w3e4r!!

  mail:
    host: smtp.gmail.com
    port: 465
    username: suren0709@gmail.com
    address: suren0709@gmail.com
    password: fomnytoqvzmvqpcp
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true

jwt:
  secret: 4eHD683dQxu26T++rVnffSSIzwoEsqtW9enDTGGMLFo80BgWdYEoyVYvRpfW38p9
