spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-db.chgeai0qiq90.ap-northeast-2.rds.amazonaws.com:3306/library_db
    username: aws
    password: 1q2w3e4r!!

  mail:
    host: smtp.gmail.com
    port: 465
    username: suren0709@gmail.com
    address: suren0709@gmail.com
    password: fomnytoqvzmvqpcp
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 33229433863-shgm9il3q5qs3t501djk1404qrl20k9o.apps.googleusercontent.com
            clientSecret: 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


jwt:
  secret: 4eHD683dQxu26T++rVnffSSIzwoEsqtW9enDTGGMLFo80BgWdYEoyVYvRpfW38p9
